//PACKAGE COM.EXCILYS.FORMATION.WEBPROJECT.CONTROLLER;
//
//IMPORT JAVA.IO.IOEXCEPTION;
//IMPORT JAVA.UTIL.ARRAYLIST;
//IMPORT JAVA.UTIL.LIST;
//
//IMPORT JAVAX.SERVLET.SERVLETCONFIG;
//IMPORT JAVAX.SERVLET.SERVLETEXCEPTION;
//IMPORT JAVAX.SERVLET.HTTP.HTTPSERVLETREQUEST;
//IMPORT JAVAX.SERVLET.HTTP.HTTPSERVLETRESPONSE;
//
//IMPORT ORG.SPRINGFRAMEWORK.BEANS.FACTORY.ANNOTATION.AUTOWIRED;
//IMPORT ORG.SPRINGFRAMEWORK.UI.MODEL;
//IMPORT ORG.SPRINGFRAMEWORK.WEB.BIND.ANNOTATION.REQUESTMAPPING;
//IMPORT ORG.SPRINGFRAMEWORK.WEB.BIND.ANNOTATION.REQUESTMETHOD;
//IMPORT ORG.SPRINGFRAMEWORK.STEREOTYPE.CONTROLLER;
//IMPORT ORG.SPRINGFRAMEWORK.WEB.CONTEXT.SUPPORT.SPRINGBEANAUTOWIRINGSUPPORT;
//
//IMPORT COM.EXCILYS.FORMATION.WEBPROJECT.COMMON.VALIDATOR;
//IMPORT COM.EXCILYS.FORMATION.WEBPROJECT.DTO.COMPUTERDTO;
//IMPORT COM.EXCILYS.FORMATION.WEBPROJECT.OM.COMPANY;
//IMPORT COM.EXCILYS.FORMATION.WEBPROJECT.OM.COMPUTER;
//IMPORT COM.EXCILYS.FORMATION.WEBPROJECT.SERVICE.IMPL.MAINSERVICEIMPL;
//
///**
// * 
// * @AUTHOR EXCILYS
// *
// */
//@REQUESTMAPPING("/ADDCOMPUTER")
//@CONTROLLER
//PUBLIC CLASS ADDCONTROLLER EXTENDS FORMCONTROLLER{
//	
//	@AUTOWIRED
//	PRIVATE MAINSERVICEIMPL MAINSERVICE;
//	
//	@REQUESTMAPPING(METHOD = REQUESTMETHOD.GET)
//	PUBLIC STRING GETADDFORM(MODEL MODEL) {		
//		
//		LIST<COMPANY> COMPANYLIST = (ARRAYLIST<COMPANY>)MAINSERVICE.GETLISTCOMPANY();
//		MODEL.ADDATTRIBUTE("COMPANYLIST", COMPANYLIST);
//		MODEL.ADDATTRIBUTE("COMPANYLISTSIZE", COMPANYLIST.SIZE());
//		
//		RETURN "ADDCOMPUTER";
//	}
//	
//	@REQUESTMAPPING(METHOD = REQUESTMETHOD.POST)
//	PUBLIC VOID POSTADDFORM(HTTPSERVLETREQUEST REQUEST,HTTPSERVLETRESPONSE RESPONSE) THROWS SERVLETEXCEPTION, IOEXCEPTION {		
//			
//		COMPUTERDTO COMPUTERDTO = RETRIEVECOMPUTERDTO(REQUEST,RESPONSE);
//		COMPUTER COMPUTER = RETRIEVECOMPUTER(COMPUTERDTO);
//		
//		LIST ERRORLIST = VALIDATOR.CHECK(COMPUTERDTO);
//		
//		IF (!(VALIDATOR.VALIDATE(ERRORLIST))) {
//			
//			LIST<COMPANY> COMPANYLIST = (ARRAYLIST<COMPANY>)MAINSERVICE.GETLISTCOMPANY();
//			REQUEST.SETATTRIBUTE("COMPANYLIST", COMPANYLIST);
//			REQUEST.SETATTRIBUTE("COMPANYLISTSIZE", COMPANYLIST.SIZE());
//			REQUEST.SETATTRIBUTE("ERRORLIST", ERRORLIST);
//			
//			THIS.GETSERVLETCONTEXT().GETREQUESTDISPATCHER("/WEB-INF/ADDCOMPUTER.JSP").FORWARD(REQUEST,RESPONSE);
//		}
//		ELSE { 
//			MAINSERVICE.INSERTCOMPUTER(COMPUTER);
//			
//			THIS.GETSERVLETCONTEXT().GETREQUESTDISPATCHER("/INDEX.JSP").FORWARD(REQUEST,RESPONSE);
//		}
//	}	
//}